/**
 * @file ErrorGen.hpp
 * @author Misha Solodilov (mihsolodilov2015@gmail.com)
 * @brief Error code generation
 *
 * @version 1.0
 * @date 12.06.2025
 *
 * @copyright Copyright (c) 2025
 *
 */

// DEF_ERROR(code)

DEF_ERROR(EVERYTHING_FINE)

DEF_ERROR(ERROR_BAD_ARGS)
DEF_ERROR(ERROR_EMPTY_STRING)
DEF_ERROR(ERROR_BAD_FILE)
DEF_ERROR(ERROR_BAD_FOLDER)
DEF_ERROR(ERROR_BAD_ID)
DEF_ERROR(ERROR_BAD_RECURSION)
DEF_ERROR(ERROR_BAD_THREAD)
DEF_ERROR(ERROR_BAD_VALUE)
DEF_ERROR(ERROR_INDEX_OUT_OF_BOUNDS)
DEF_ERROR(ERROR_LINUX)
DEF_ERROR(ERROR_NO_MEMORY)
DEF_ERROR(ERROR_NOT_FOUND)
DEF_ERROR(ERROR_NULLPTR)
DEF_ERROR(ERROR_SDL)
DEF_ERROR(ERROR_STD)
DEF_ERROR(ERROR_SYNTAX)
DEF_ERROR(ERROR_UNINITIALIZED)
DEF_ERROR(ERROR_ZERO_DIVISION)
DEF_ERROR(EXIT)
