//NOLINTBEGIN

// DEF_ERROR(code)

DEF_ERROR(EVERYTHING_FINE)
DEF_ERROR(ERROR_NULLPTR)
DEF_ERROR(ERROR_BAD_FILE)
DEF_ERROR(ERROR_INDEX_OUT_OF_BOUNDS)
DEF_ERROR(ERROR_NO_MEMORY)
DEF_ERROR(ERROR_BAD_VALUE)
DEF_ERROR(ERROR_ZERO_DIVISION)
DEF_ERROR(ERROR_SYNTAX)
DEF_ERROR(ERROR_NOT_FOUND)
DEF_ERROR(ERROR_SDL)
DEF_ERROR(ERROR_BAD_ID)
DEF_ERROR(ERROR_NO_ROOT)
DEF_ERROR(ERROR_BAD_RECURSION)
DEF_ERROR(ERROR_UNINITIALIZED)
DEF_ERROR(EXIT)

//NOLINTEND
